configName: poop_config
folderName: poop
format_version: v1.0
frameworkPath: ../../Harmony3
processor: ATSAME70Q21B
projectName: poop
settings:
  PackageFilter: crypto;csp_apps_sam_e70_s70_v70_v71;dev_packs;net;core;bsp;quick_docs;usb;bt;cryptoauthlib;csp;aws_cloud;core_apps_sam_e70_s70_v70_v71
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/SAME70_DFP/4.6.98/same70b/atdf/ATSAME70Q21B.atdf
